2021-03-20 00:32:11,219 INFO: Microblog startup [in /home/sebastian/workspaceu/test_fullStack/app/__init__.py:43]
2021-03-20 00:32:14,194 ERROR: Exception on /index [GET] [in /home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/sebastian/workspaceu/test_fullStack/app/routes.py", line 33, in index
    return render_template('index.html', title='Home Page', posts=posts)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/sebastian/workspaceu/test_fullStack/app/templates/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/sebastian/workspaceu/test_fullStack/app/templates/base.html", line 39, in top-level template code
    {% block content %}{% endblock %}
  File "/home/sebastian/workspaceu/test_fullStack/app/templates/index.html", line 7, in block "content"
    {{ form.hidden_tag() }}
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-03-20 00:32:34,928 INFO: Microblog startup [in /home/sebastian/workspaceu/test_fullStack/app/__init__.py:43]
2021-03-20 00:33:12,002 INFO: Microblog startup [in /home/sebastian/workspaceu/test_fullStack/app/__init__.py:43]
2021-03-20 00:35:08,699 INFO: Microblog startup [in /home/sebastian/workspaceu/test_fullStack/app/__init__.py:43]
2021-03-20 00:35:32,364 INFO: Microblog startup [in /home/sebastian/workspaceu/test_fullStack/app/__init__.py:43]
2021-03-20 00:35:36,495 ERROR: Exception on /index [POST] [in /home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/sebastian/workspaceu/test_fullStack/app/routes.py", line 17, in index
    post = Post(body=form.post.data, author=current_user)
NameError: name 'Post' is not defined
2021-03-20 00:36:37,842 INFO: Microblog startup [in /home/sebastian/workspaceu/test_fullStack/app/__init__.py:43]
2021-03-20 00:42:10,526 INFO: Microblog startup [in /home/sebastian/workspaceu/test_fullStack/app/__init__.py:43]
2021-03-20 12:14:55,969 INFO: Microblog startup [in /home/sebastian/workspaceu/test_fullStack/app/__init__.py:43]
2021-03-20 12:23:19,444 INFO: Microblog startup [in /home/sebastian/workspaceu/test_fullStack/app/__init__.py:43]
2021-03-20 12:23:22,489 ERROR: Exception on /index [GET] [in /home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/sebastian/workspaceu/test_fullStack/app/routes.py", line 27, in index
    return render_template('index.html', title='Home Page', posts=posts, form=form)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/sebastian/workspaceu/test_fullStack/app/templates/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/sebastian/workspaceu/test_fullStack/app/templates/base.html", line 40, in top-level template code
    {% block content %}{% endblock %}
  File "/home/sebastian/workspaceu/test_fullStack/app/templates/index.html", line 19, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2021-03-20 12:23:23,697 ERROR: Exception on /explore [GET] [in /home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sebastian/workspaceu/test_fullStack/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/sebastian/workspaceu/test_fullStack/app/routes.py", line 35, in explore
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2021-03-20 12:23:54,326 INFO: Microblog startup [in /home/sebastian/workspaceu/test_fullStack/app/__init__.py:43]
